export {
  buildProviderCommand,
  classifyProviderError,
  detectProviderFatalError,
  detectProviderStreamingModeError,
  extractProviderSessionId,
  getProviderAdapter,
  listProviderAdapters,
  parseProviderChunk,
  recoverProviderStructuredOutput,
  resolveModelSpec,
  supportsProviderStructuredOutputRecovery,
  NO_MESSAGES_RETURNED,
  STREAMING_MODE_ERROR,
  type StreamingModeError,
  type StructuredOutputRecovery,
} from './adapters';
export {
  providerExecutableSchemaVersion,
  runProviderExecutable,
  type ContractEnvelope,
  type ContractErrorEnvelope,
  type ContractErrorObject,
  type ContractEvidence,
  type ContractSuccessEnvelope,
  type ProviderExecutableCommand,
  type ProviderExecutableOptions,
  type ProviderExecutableResponse,
} from './contract';
export {
  spawnProcessRunner,
  type ProcessResult,
  type ProcessRunner,
  type ProcessRunnerOptions,
} from './process-runner';
export {
  runOmpRpcTask,
  type OmpRpcSessionEvidence,
  type OmpRpcSpawnEvidence,
  type OmpRpcTaskHooks,
  type OmpRpcTaskRequest,
  type OmpRpcTaskResult,
} from './omp-rpc-driver';
export { buildOmpPrompt } from './adapters/omp';
export { DEFAULT_OMP_RPC_DECODER_LIMITS } from './omp-rpc-protocol';
export { ABORT_GRACE_MS, EXIT_GRACE_MS } from './omp-rpc-bounds';
export { OMP_SUPPORTED_VERSION } from './omp-release';
export type { OmpSessionLaunch, VerifiedOmpPartition, VerifiedOmpSessionFile } from './omp-rpc-session';
export {
  detectRuntimeProviderCliFeatures,
  prepareSingleAgentProviderCommand,
  probeRuntimeProviderCli,
  type PreparedSingleAgentProviderCommand,
  type RuntimeProviderProbe,
  type SingleAgentProviderCommandInput,
} from './single-agent-runtime';
export {
  credentialEnvKeysForProvider,
  findProviderRegistryEntry,
  getProviderRegistryEntry,
  knownProviderNames,
  listProviderRegistryEntries,
  normalizeProviderName,
  providerAliasMap,
  providerAliases,
  providerIds,
  providerRegistry,
  resolveProviderCommand,
  supportsProviderCapability,
  supportsProviderOutputReformatting,
} from './provider-registry';

export type {
  AgentCliProviderHelperMetadata,
  BuildProviderCommandOptions,
  CleanupMetadata,
  CliFeatureOverrides,
  AcpCliFeatures,
  ClaudeCliFeatures,
  CodexCliFeatures,
  CopilotCliFeatures,
  CommandSpec,
  ErrorClassification,
  ErrorClassificationKind,
  GatewayBuildOptions,
  GatewayCliFeatures,
  GatewayProtocol,
  GatewayToolPolicy,
  GeminiCliFeatures,
  KnownProviderName,
  LevelModelSpec,
  LevelOverrides,
  ModelCatalogEntry,
  ModelLevel,
  ModelSpec,
  OmpCliFeatures,
  OpencodeCliFeatures,
  OutputEvent,
  OutputFormat,
  PiCliFeatures,
  ProviderAdapter,
  ProviderCapabilities,
  ProviderCapabilityState,
  ProviderCommandSpec,
  ProviderDocsMetadata,
  ProviderInvokeSpec,
  ProviderAlias,
  ProviderCliFeatures,
  ProviderId,
  ProviderRegistryEntry,
  StructuredOutputRecoveryAdapter,
  StructuredOutputProviderRegistryEntry,
  UnstructuredOutputProviderRegistryEntry,
  RedactionMetadata,
  ReasoningEffort,
  ResolvedGatewayBuildOptions,
  ResolvedModelSpec,
  ResultEvent,
  TextEvent,
  ThinkingEvent,
  ToolCallEvent,
  ToolResultEvent,
  WarningMetadata,
  WebSearchAttestation,
} from './types';

import type { AgentCliProviderHelperMetadata } from './types';

export const agentCliProviderHelperMetadata: Readonly<AgentCliProviderHelperMetadata> = {
  packageName: '@the-open-engine/zeroshot',
  buildOutputDir: 'lib/agent-cli-provider',
  contractVersion: 1,
  adapterVersion: '1',
};
