//! Shared "cancel a subscription, then assert the at-most-one-post-cancel-leak model" assertion
//! for `logs`/`agent_attach` NDJSON client tests: `NdjsonLogsEventStream` and
//! `NdjsonAgentAttachEventStream` are both generated by the same
//! `openengine_cluster_client::ndjson_subscription::impl_ndjson_event_subscription` macro
//! invocation and share the same `next`/`cancel` shape, so this exists exactly once instead of
//! being hand-copied per capability. Used by `tests/logs.rs` and `tests/agent_attach.rs`.

use std::fmt::Debug;
use std::future::Future;
use std::time::Duration;

use openengine_cluster_client::{
    AgentAttachEventOrClosed, ClientError, ClusterClient, LogEventOrClosed,
    NdjsonAgentAttachEventStream, NdjsonLogsEventStream, NdjsonTransport,
};
use openengine_cluster_protocol::GetParams;
use tokio::io::{AsyncRead, AsyncWrite};

/// Minimal shape shared by every generated `Ndjson*EventStream`: `next`/`cancel` with the exact
/// signatures `impl_ndjson_event_subscription!` produces.
pub trait NdjsonEventStream {
    type EventOrClosed: Debug;
    async fn next(&mut self) -> Option<Result<Self::EventOrClosed, ClientError>>;
    async fn cancel(&self) -> Result<(), ClientError>;
}

impl<R, W> NdjsonEventStream for NdjsonLogsEventStream<'_, R, W>
where
    R: AsyncRead + Send + Unpin + 'static,
    W: AsyncWrite + Send + Unpin + 'static,
{
    type EventOrClosed = LogEventOrClosed;
    async fn next(&mut self) -> Option<Result<Self::EventOrClosed, ClientError>> {
        NdjsonLogsEventStream::next(self).await
    }
    async fn cancel(&self) -> Result<(), ClientError> {
        NdjsonLogsEventStream::cancel(self).await
    }
}

impl<R, W> NdjsonEventStream for NdjsonAgentAttachEventStream<'_, R, W>
where
    R: AsyncRead + Send + Unpin + 'static,
    W: AsyncWrite + Send + Unpin + 'static,
{
    type EventOrClosed = AgentAttachEventOrClosed;
    async fn next(&mut self) -> Option<Result<Self::EventOrClosed, ClientError>> {
        NdjsonAgentAttachEventStream::next(self).await
    }
    async fn cancel(&self) -> Result<(), ClientError> {
        NdjsonAgentAttachEventStream::cancel(self).await
    }
}

/// Cancels `stream`, forces a synchronous unary round trip over `transport` to guarantee the
/// server's read loop has already applied the preceding cancel notification, publishes two
/// further "leak probe" events via `publish`, then asserts the at-most-one-post-cancel-leak model:
/// the server-side subscription task may already have been parked awaiting the next live event at
/// the moment cancellation was processed, so at most one further event may still be delivered
/// before it observes cancellation and stops for good -- and if one is, it must be exactly the
/// first probe (`"maybe-leaked"`), never the second. `classify` maps a delivered event to its
/// probe text; returning `None` for a `Closed` item or any unexpected event variant panics with
/// that item's `Debug` output.
pub async fn assert_cancel_stops_further_delivery<S, R, W, F>(
    stream: &mut S,
    transport: &NdjsonTransport<R, W>,
    mut publish: impl FnMut(&'static str) -> F,
    mut classify: impl FnMut(&S::EventOrClosed) -> Option<String>,
) where
    S: NdjsonEventStream,
    R: AsyncRead + Send + Unpin + 'static,
    W: AsyncWrite + Send + Unpin + 'static,
    F: Future<Output = ()>,
{
    stream.cancel().await.unwrap();
    ClusterClient::new(transport)
        .get(GetParams::default())
        .await
        .unwrap();

    publish("maybe-leaked").await;
    publish("must-never-arrive").await;

    let mut leaked = Vec::new();
    loop {
        match tokio::time::timeout(Duration::from_millis(300), stream.next()).await {
            Ok(Some(Ok(item))) => match classify(&item) {
                Some(text) => leaked.push(text),
                None => panic!("unexpected notification after cancel: {item:?}"),
            },
            Ok(Some(Err(e))) => panic!("unexpected error: {e}"),
            Ok(None) | Err(_) => break,
        }
    }
    assert!(
        leaked.len() <= 1,
        "cancelled subscription received more than one post-cancel event: {leaked:?}"
    );
    if let Some(message) = leaked.first() {
        assert_eq!(
            message, "maybe-leaked",
            "cancellation failed to stop delivery before the next published event"
        );
    }
}
