/**
 * DO NOT EDIT.
 *
 * Generated by `npm run generate:cluster-protocol-types` from the authoritative protocol schemas:
 *   protocol/openengine-cluster/v1/schema.json
 *   protocol/openengine-cluster/v1/graph.schema.json
 *   protocol/openengine-cluster/v1/compiled-ir.schema.json
 *   protocol/openengine-cluster/v1/worker.schema.json
 *
 * Regenerate after any protocol schema change. `npm run check:cluster-protocol-types` fails CI on drift.
 */

/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "PayloadType".
 */
export type PayloadType =
  | {
      kind: 'null';
    }
  | {
      kind: 'boolean';
    }
  | {
      kind: 'integer';
    }
  | {
      kind: 'number';
    }
  | {
      kind: 'string';
    }
  | {
      fields: {
        [k: string]: RecordField;
      };
      kind: 'record';
    }
  | {
      items: PayloadType;
      kind: 'array';
    }
  | {
      kind: 'enum';
      /**
       * @minItems 1
       * @maxItems 4096
       */
      values: [string, ...string[]];
    };
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "PolicyDefault".
 */
export type PolicyDefault = 'deny';
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "GraphProfile".
 */
export type GraphProfile = 'openengine.graph.full/v1' | 'openengine.graph.single-worker/v1';
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "GraphNode".
 */
export type GraphNode =
  | {
      attempts: number;
      input: PayloadType;
      inputBindings: InputBinding[];
      kind: 'step';
      name: string;
      output: PayloadType;
      timeoutMs: number;
      worker: string;
      writeBindings: WriteBinding[];
    }
  | {
      attempts: number;
      diagnostic: PayloadType;
      input: PayloadType;
      inputBindings: InputBinding[];
      kind: 'verifier';
      name: string;
      output: PayloadType;
      signals: {
        /**
         * @minItems 1
         * @maxItems 4096
         */
        [k: string]: [string, ...string[]];
      };
      timeoutMs: number;
      worker: string;
      writeBindings: WriteBinding[];
    }
  | {
      children: NonEmptyVecOf_GraphNode;
      kind: 'seq';
      name: string;
      promotedStatePaths: [string, ...string[]][];
      state: PayloadType;
    }
  | {
      branches: NonEmptyVecOf_ChoiceBranch;
      kind: 'choice';
      name: string;
      otherwise?: GraphNode | null;
      promotedStatePaths: [string, ...string[]][];
      state: PayloadType;
    }
  | {
      branches: NonEmptyVecOf_GraphNode;
      join: Join;
      kind: 'par';
      name: string;
      promotedStatePaths: [string, ...string[]][];
      state: PayloadType;
    }
  | {
      body: GraphNode;
      kind: 'loop';
      maxIterations: number;
      name: string;
      promotedStatePaths: [string, ...string[]][];
      state: PayloadType;
      until: Guard;
    }
  | {
      body: GraphNode;
      kind: 'map';
      maxItems: number;
      name: string;
      over: DataSelector;
      promotedStatePaths: [string, ...string[]][];
      state: PayloadType;
    }
  | {
      bindings: InputBinding[];
      kind: 'succeed';
      name: string;
      output: PayloadType;
    }
  | {
      kind: 'fail';
      name: string;
      reason: string;
    };
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "DataSelector".
 */
export type DataSelector =
  | {
      /**
       * @minItems 1
       * @maxItems 64
       */
      path: [string, ...string[]];
      source: 'state';
    }
  | {
      /**
       * @minItems 1
       * @maxItems 64
       */
      path: [string, ...string[]];
      source: 'item';
    };
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "NodeOutputChannel".
 */
export type NodeOutputChannel = 'out' | 'signal' | 'diagnostic';
/**
 * @minItems 1
 * @maxItems 4096
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "NonEmptyVec_of_GraphNode".
 */
export type NonEmptyVecOf_GraphNode = [GraphNode, ...GraphNode[]];
/**
 * @minItems 1
 * @maxItems 4096
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "NonEmptyVec_of_ChoiceBranch".
 */
export type NonEmptyVecOf_ChoiceBranch = [ChoiceBranch, ...ChoiceBranch[]];
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "Guard".
 */
export type Guard =
  | {
      kind: 'in';
      /**
       * @minItems 1
       * @maxItems 4096
       */
      labels: [string, ...string[]];
      value: ControlSelector;
    }
  | {
      guards: NonEmptyVecOf_Guard;
      kind: 'all';
    }
  | {
      guards: NonEmptyVecOf_Guard;
      kind: 'any';
    }
  | {
      guard: Guard;
      kind: 'not';
    }
  | {
      count: number;
      kind: 'k_of_n';
      /**
       * @minItems 1
       * @maxItems 4096
       */
      labels: [string, ...string[]];
      values: NonEmptyVecOf_ControlSelector;
    }
  | {
      count: number;
      kind: 'k_of_map';
      /**
       * @minItems 1
       * @maxItems 4096
       */
      labels: [string, ...string[]];
      value: ControlSelector;
    };
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "ControlSource".
 */
export type ControlSource = 'signal' | 'error' | 'group';
/**
 * @minItems 1
 * @maxItems 4096
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "NonEmptyVec_of_Guard".
 */
export type NonEmptyVecOf_Guard = [Guard, ...Guard[]];
/**
 * @minItems 1
 * @maxItems 4096
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "NonEmptyVec_of_ControlSelector".
 */
export type NonEmptyVecOf_ControlSelector = [ControlSelector, ...ControlSelector[]];
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "Join".
 */
export type Join =
  | {
      kind: 'all';
    }
  | {
      kind: 'any';
    }
  | {
      count: number;
      kind: 'quorum';
    }
  | {
      kind: 'first';
      when: Guard;
    };
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "SubscriptionCloseReason".
 */
export type SubscriptionCloseReason = 'done' | 'SLOW_CONSUMER';
/**
 * The closed public agent-attach progress algebra. This is the only representable shape:
 * reasoning, tools, provider frames, usage, and session identifiers have no variant. `Working`
 * and `Settled` are empty struct variants rather than bare units: serde's internally tagged enum
 * deserialization silently ignores unknown fields on a unit variant regardless of
 * `deny_unknown_fields`, which would otherwise let an unrepresentable field ride along
 * undetected on either of these two variants.
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "AgentAttachEvent".
 */
export type AgentAttachEvent =
  | {
      type: 'working';
    }
  | {
      text: string;
      type: 'output';
    }
  | {
      type: 'settled';
    };
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "Phase".
 */
export type Phase = 'empty' | 'admitting' | 'running' | 'finished' | 'deleting';
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "RedactionClass".
 */
export type RedactionClass = 'public' | 'internal' | 'confidential' | 'restricted';
/**
 * Descriptive only, like [`FaultRetryDisposition`]: naming `Retry` never itself retries or
 * authorizes a retry.
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "FaultAction".
 */
export type FaultAction = 'none' | 'retry' | 'wait' | 'escalate' | 'abort';
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "FaultCode".
 */
export type FaultCode =
  | 'unavailable'
  | 'resource_exhausted'
  | 'deadline_exceeded'
  | 'permission_denied'
  | 'failed_precondition'
  | 'not_found'
  | 'aborted'
  | 'internal'
  | 'unknown';
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "FaultConsequence".
 */
export type FaultConsequence =
  | 'turn_failed'
  | 'run_failed'
  | 'run_degraded'
  | 'no_observable_effect';
/**
 * Descriptive only: no `BackendFault` and no `fault` event ever performs or authorizes a retry.
 * Event ordering and emission never themselves change terminal semantics.
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "FaultRetryDisposition".
 */
export type FaultRetryDisposition =
  | 'retryable'
  | 'retryable_after_backoff'
  | 'not_retryable'
  | 'indeterminate';
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "FaultSeverity".
 */
export type FaultSeverity = 'info' | 'warning' | 'error' | 'critical';
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "RequestId".
 */
export type RequestId = string | number;
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "DispatchState".
 */
export type DispatchState = 'active' | 'suspended' | 'draining' | 'force_stopping' | 'stopped';
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "LogLevel".
 */
export type LogLevel = 'trace' | 'debug' | 'info' | 'warn' | 'error';
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "StopMode".
 */
export type StopMode = 'drain' | 'force';
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "DiagnosticPathSegment".
 */
export type DiagnosticPathSegment =
  | {
      kind: 'field';
      name: string;
    }
  | {
      index: number;
      kind: 'index';
    }
  | {
      kind: 'node';
      name: string;
    };
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "DiagnosticSeverity".
 */
export type DiagnosticSeverity = 'error' | 'warning' | 'info';
/**
 * The closed public event algebra. `Phase` folds the observable cluster status (admission
 * commit, update, suspend/resume, stop-request); `NodeBegin`/`NodeEnd` are a testkit-only
 * synthetic hook decoupled from the real dispatch/lease turn mechanism, since no native graph
 * executor exists yet; `Bookmark` advances the cursor without changing folded public state;
 * `Fault` carries a durable, backend-neutral projected `BackendFault`: it correlates to the
 * enclosing `EventNotification.run_id` plus its own optional opaque `executionRef`, and its
 * ordering/emission never itself authorizes a retry or changes terminal semantics -- it folds to
 * no public status change, exactly like `Bookmark`; `Finished` is always the last event for a
 * run.
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "WatchEvent".
 */
export type WatchEvent =
  | {
      admission?: AdmissionTransition | null;
      status: ClusterStatus;
      type: 'phase';
    }
  | {
      input: unknown;
      node: NodeAddress;
      type: 'node_begin';
    }
  | {
      node: NodeAddress;
      outcome: WorkerOutcome;
      type: 'node_end';
    }
  | {
      type: 'bookmark';
    }
  | {
      fault: BackendFault;
      type: 'fault';
    }
  | {
      final_status: ClusterStatus;
      stop_mode?: StopMode | null;
      type: 'finished';
    };
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "WorkerOutcome".
 */
export type WorkerOutcome = WorkerOutcomeWire & {
  [k: string]: unknown;
};
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "WorkerOutcomeWire".
 */
export type WorkerOutcomeWire =
  | {
      artifacts: ArtifactRef[];
      output: unknown;
      status: 'verified';
    }
  | {
      artifacts: ArtifactRef[];
      diagnostic: unknown;
      output: unknown;
      signals: {
        [k: string]: string;
      };
      status: 'verifier';
    }
  | {
      code: WorkerErrorCode;
      reason: WorkerFailureReason;
      status: 'error';
    };
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "WorkerErrorCode".
 */
export type WorkerErrorCode = 'timeout' | 'crash' | 'malformed' | 'refusal';
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "WorkerFailureReason".
 */
export type WorkerFailureReason =
  | 'declared_failure'
  | 'policy_denied'
  | 'interactive_input_required'
  | 'authentication_required'
  | 'malformed_result';
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "GraphDiagnosticCode".
 */
export type GraphDiagnosticCode =
  | 'schema_safety'
  | 'reachability'
  | 'choice_exhaustiveness'
  | 'loop_exit_satisfiability'
  | 'missing_bound'
  | 'write_conflict'
  | 'ceiling_exceeded'
  | 'cyclic_reference'
  | 'undefined_read'
  | 'invalid_graph_shape';
/**
 * @minItems 1
 * @maxItems 4096
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "NonEmptyVec_of_FieldPath".
 */
export type NonEmptyVecOf_FieldPath = [[string, ...string[]], ...[string, ...string[]][]];
/**
 * @minItems 1
 * @maxItems 4096
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "NonEmptyVec_of_NodeName".
 */
export type NonEmptyVecOf_NodeName = [string, ...string[]];
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "TerminationWitness".
 */
export type TerminationWitness =
  | {
      kind: 'acyclic';
      order: NonEmptyVecOf_NodeName;
    }
  | {
      kind: 'bounded';
      maxIterations: number;
      ranking: NonEmptyVecOf_FieldPath;
    };
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "AutonomyPolicy".
 */
export type AutonomyPolicy = 'strict';
/**
 * Opaque registry identity. The handle can select secret material but can never contain it.
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "CredentialHandle".
 */
export type CredentialHandle = string;
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "LegacyShipRequest".
 */
export type LegacyShipRequest =
  | {
      artifacts?: {
        [k: string]: unknown;
      };
      issue: string;
      prompt?: null;
      source?: 'issue';
      [k: string]: unknown;
    }
  | {
      artifacts?: {
        [k: string]: unknown;
      };
      issue?: null;
      prompt: string;
      source?: 'prompt';
      [k: string]: unknown;
    }
  | {
      artifacts?: {
        [k: string]: unknown;
      };
      issue?: null;
      prompt?: null;
      source?: 'artifact';
      [k: string]: unknown;
    };
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "LegacyShipStatus".
 */
export type LegacyShipStatus = 'succeeded' | 'failed';
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "WorkerProtocolBinding".
 */
export type WorkerProtocolBinding =
  | {
      profile: 'openengine.worker.acp/v1';
      protocol: 'acp';
      version: '1';
    }
  | {
      profile: 'openengine.worker.a2a/1.0';
      protocol: 'a2a';
      version: '1.0';
    }
  | {
      profile: 'legacy.zeroshot.ship/v1';
      protocol: 'legacy_zeroshot';
      version: '1';
    }
  | {
      profile: 'openengine.worker.builtin/v1';
      protocol: 'builtin';
      version: '1';
    };

/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "AdmissionTransition".
 */
export interface AdmissionTransition {
  runId: string;
  seedInput: unknown;
  spec: GraphSpec;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "GraphSpec".
 */
export interface GraphSpec {
  initialInput: PayloadType;
  policy: PolicyBinding;
  profile: GraphProfile;
  root: GraphNode;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "RecordField".
 */
export interface RecordField {
  required: boolean;
  type: PayloadType;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "PolicyBinding".
 */
export interface PolicyBinding {
  default: PolicyDefault;
  policy: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "InputBinding".
 */
export interface InputBinding {
  /**
   * @minItems 1
   * @maxItems 64
   */
  target: [string, ...string[]];
  value: DataSelector;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "WriteBinding".
 */
export interface WriteBinding {
  /**
   * @minItems 1
   * @maxItems 64
   */
  target: [string, ...string[]];
  value: NodeOutputSelector;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "NodeOutputSelector".
 */
export interface NodeOutputSelector {
  channel: NodeOutputChannel;
  node: string;
  /**
   * @minItems 1
   * @maxItems 64
   */
  path: [string, ...string[]];
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "ChoiceBranch".
 */
export interface ChoiceBranch {
  node: GraphNode;
  when: Guard;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "ControlSelector".
 */
export interface ControlSelector {
  field?: string | null;
  name: string;
  source: ControlSource;
}
/**
 * Wire body of the terminal `subscription/closed` server notification for an `agent/attach`
 * subscription. Deliberately carries no cursor field -- `agent/attach` gives a type-level
 * "cursorless" guarantee, unlike [`crate::SubscriptionClosedNotification`].
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "AgentAttachClosedNotification".
 */
export interface AgentAttachClosedNotification {
  reason: SubscriptionCloseReason;
  subscriptionId: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "AgentAttachEventNotification".
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "AgentAttachEventNotificationWire".
 */
export interface AgentAttachEventNotificationWire {
  event: AgentAttachEvent;
  subscriptionId: string;
}
/**
 * `agent/attach` establishment parameters: the named `{execution}` request. Deliberately closed,
 * rejecting any unknown field.
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "AgentAttachParams".
 */
export interface AgentAttachParams {
  execution: string;
}
/**
 * The `agent/attach` establishment result: only a `subscriptionId`. Deliberately carries no
 * `runId` or `atCursor` -- `agent/attach` is not run-scoped and has no cursor.
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "AgentAttachResult".
 */
export interface AgentAttachResult {
  subscriptionId: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "ApplyParams".
 */
export interface ApplyParams {
  dryRun?: boolean;
  graph: GraphSpec;
  idempotencyKey?: string;
  ifGeneration?: number;
  input?: unknown;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "ApplyResult".
 */
export interface ApplyResult {
  deduped: boolean;
  diff?: GraphDiff | null;
  generation?: number | null;
  phase: Phase;
  runId?: string | null;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "GraphDiff".
 */
export interface GraphDiff {
  added: string[];
  changed: string[];
  removed: string[];
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "ArtifactLineage".
 */
export interface ArtifactLineage {
  attempt: number;
  generation: number;
  runId: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "ArtifactProducer".
 */
export interface ArtifactProducer {
  node: string;
  worker: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "ArtifactRef".
 */
export interface ArtifactRef {
  artifactId: string;
  byteLength: number;
  lineage: ArtifactLineage;
  mediaType: string;
  producer: ArtifactProducer;
  redaction: RedactionClass;
  sha256: string;
  typeId: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "BackendFault".
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "BackendFaultWire".
 */
export interface BackendFault {
  action: FaultAction;
  code: FaultCode;
  consequence: FaultConsequence;
  eventId: string;
  executionRef?: string | null;
  retry: FaultRetryDisposition;
  severity: FaultSeverity;
  /**
   * @maxItems 8
   */
  source:
    | []
    | [FaultSourceFrame]
    | [FaultSourceFrame, FaultSourceFrame]
    | [FaultSourceFrame, FaultSourceFrame, FaultSourceFrame]
    | [FaultSourceFrame, FaultSourceFrame, FaultSourceFrame, FaultSourceFrame]
    | [FaultSourceFrame, FaultSourceFrame, FaultSourceFrame, FaultSourceFrame, FaultSourceFrame]
    | [
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame
      ]
    | [
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame
      ]
    | [
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame,
        FaultSourceFrame
      ];
  summary: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "FaultSourceFrame".
 */
export interface FaultSourceFrame {
  component: string;
}
/**
 * Wire body of the `$/cancelRequest` client notification: best-effort cancellation of an
 * in-flight unary request by its `RequestId`. Unknown or already-completed ids are a silent
 * no-op; cancelling after the backend has committed leaves that committed state unchanged and
 * emits no response or compensation.
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "CancelRequestParams".
 */
export interface CancelRequestParams {
  id: RequestId;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "ClusterStatus".
 */
export interface ClusterStatus {
  atCursor?: string | null;
  currentRunId?: string | null;
  observedGeneration?: number | null;
  operational?: OperationalStatus | null;
  phase: Phase;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "OperationalStatus".
 */
export interface OperationalStatus {
  dispatchState: DispatchState;
  inFlight: number;
  labels: Labels;
  logLevel: LogLevel;
  stopMode?: StopMode | null;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "Labels".
 */
export interface Labels {
  [k: string]: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "DeleteParams".
 */
export interface DeleteParams {
  idempotencyKey: string;
  ifGeneration: number;
  ifRunId?: string | null;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "DeleteResult".
 */
export interface DeleteResult {
  atCursor?: string | null;
  deduped: boolean;
  deleted: boolean;
  generation?: number | null;
  phase: Phase;
  runId?: string | null;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "DomainErrorData".
 */
export interface DomainErrorData {
  code: string;
  details?: unknown;
  [k: string]: unknown;
}
/**
 * Wire body of the generic `event` server notification.
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "EventNotification".
 */
export interface EventNotification {
  cursor: string;
  event: WatchEvent;
  runId: string;
  subscriptionId: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "NodeAddress".
 */
export interface NodeAddress {
  attempt: number;
  node: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "GetParams".
 */
export interface GetParams {
  atCursor?: string | null;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "GetResult".
 */
export interface GetResult {
  atCursor?: string | null;
  spec?: GraphSpec | null;
  status: ClusterStatus;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "GraphDiagnostic".
 */
export interface GraphDiagnostic {
  code: GraphDiagnosticCode;
  message: string;
  path: DiagnosticPathSegment[];
  relatedNodes: string[];
  severity: DiagnosticSeverity;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "InitializeParams".
 */
export interface InitializeParams {
  protocolVersion: 'openengine.cluster/v1';
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "InitializeResult".
 */
export interface InitializeResult {
  capabilities: ServerCapabilities;
  protocolVersion: 'openengine.cluster/v1';
  status: ClusterStatus;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "ServerCapabilities".
 */
export interface ServerCapabilities {
  agentAttach?: boolean;
  /**
   * @maxItems 2
   */
  graphProfiles?: [] | [GraphProfile] | [GraphProfile, GraphProfile];
  logs?: boolean;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "LogEventNotification".
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "LogEventNotificationWire".
 */
export interface LogEventNotificationWire {
  record: LogRecord;
  subscriptionId: string;
}
/**
 * The closed public log record shape: a level, a bounded target, and a bounded (possibly
 * redacted) message. No raw bytes, reasoning, tools, credentials, env, or provider/session IDs
 * are representable.
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "LogRecord".
 */
export interface LogRecord {
  level: LogLevel;
  message: string;
  target: string;
}
/**
 * Wire body of the terminal `subscription/closed` server notification for a `logs` subscription.
 * Deliberately carries no cursor field -- `logs` gives a type-level "cursorless" guarantee, unlike
 * [`crate::SubscriptionClosedNotification`].
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "LogsClosedNotification".
 */
export interface LogsClosedNotification {
  reason: SubscriptionCloseReason;
  subscriptionId: string;
}
/**
 * `logs` establishment parameters. v1 has zero caller filters: this is deliberately empty and
 * closed, rejecting any unknown field.
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "LogsParams".
 */
export interface LogsParams {}
/**
 * The `logs` establishment result: only a `subscriptionId`. Deliberately carries no `runId` or
 * `atCursor` -- `logs` is not run-scoped and has no cursor.
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "LogsResult".
 */
export interface LogsResult {
  subscriptionId: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "PlanParams".
 */
export interface PlanParams {
  graph: GraphSpec;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "PlanResult".
 */
export interface PlanResult {
  bounds?: StructuralBounds | null;
  diagnostics: GraphDiagnostic[];
  ok: boolean;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "StructuralBounds".
 */
export interface StructuralBounds {
  attemptsPerNode: {
    [k: string]: number;
  };
  maxNodeExecutions: number;
  peakConcurrency: number;
  termination: TerminationWitness;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "ResubmitParams".
 */
export interface ResubmitParams {
  idempotencyKey: string;
  ifGeneration: number;
  ifRunId: string;
  replacementInput?: unknown;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "ResubmitResult".
 */
export interface ResubmitResult {
  atCursor: string;
  deduped: boolean;
  generation: number;
  operational: OperationalStatus;
  phase: Phase;
  priorRunId: string;
  runId: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "RetryParams".
 */
export interface RetryParams {
  idempotencyKey: string;
  ifGeneration: number;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "RetryResult".
 */
export interface RetryResult {
  atCursor: string;
  deduped: boolean;
  generation: number;
  operational: OperationalStatus;
  phase: Phase;
  retriedTurnId: string;
  retryTurnId: string;
  runId: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "StopParams".
 */
export interface StopParams {
  idempotencyKey: string;
  ifGeneration: number;
  mode: StopMode;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "StopResult".
 */
export interface StopResult {
  acceptedMode: StopMode;
  atCursor: string;
  deduped: boolean;
  effectiveMode: StopMode;
  generation: number;
  operational: OperationalStatus;
  phase: Phase;
  runId: string;
}
/**
 * Wire body of the generic `subscription/cancel` client notification.
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "SubscriptionCancelParams".
 */
export interface SubscriptionCancelParams {
  subscriptionId: string;
}
/**
 * Wire body of the terminal `subscription/closed` server notification.
 *
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "SubscriptionClosedNotification".
 */
export interface SubscriptionClosedNotification {
  lastDeliveredCursor?: string | null;
  reason: SubscriptionCloseReason;
  subscriptionId: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "UpdateParams".
 */
export interface UpdateParams {
  idempotencyKey: string;
  ifGeneration: number;
  labels?: Labels;
  logLevel?: LogLevel;
  suspended?: boolean;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "UpdateResult".
 */
export interface UpdateResult {
  atCursor: string;
  deduped: boolean;
  generation: number;
  operational: OperationalStatus;
  phase: Phase;
  runId: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "WatchParams".
 */
export interface WatchParams {
  fromCursor?: string | null;
  runId?: string | null;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "WatchResult".
 */
export interface WatchResult {
  atCursor?: string | null;
  runId?: string | null;
  subscriptionId: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "ArtifactResultProfile".
 */
export interface ArtifactResultProfile {
  /**
   * @minItems 1
   */
  allowedMediaTypes: [string, ...string[]];
  /**
   * @minItems 1
   */
  allowedTypeIds: [string, ...string[]];
  minimumRedaction: RedactionClass;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "CapabilityPolicy".
 */
export interface CapabilityPolicy {
  autonomy: AutonomyPolicy;
  permissionPolicy: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "LegacyShipResult".
 */
export interface LegacyShipResult {
  artifacts: ArtifactRef[];
  status: LegacyShipStatus;
  summary: string;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "VerifierContract".
 */
export interface VerifierContract {
  diagnostic: PayloadType;
  signals: {
    /**
     * @minItems 1
     * @maxItems 4096
     */
    [k: string]: [string, ...string[]];
  };
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "WorkerContract".
 */
export interface WorkerContract {
  /**
   * @minItems 4
   * @maxItems 4
   */
  errors: [
    'timeout' | 'crash' | 'malformed' | 'refusal',
    'timeout' | 'crash' | 'malformed' | 'refusal',
    'timeout' | 'crash' | 'malformed' | 'refusal',
    'timeout' | 'crash' | 'malformed' | 'refusal'
  ];
  input: PayloadType;
  output: PayloadType;
  verifier?: VerifierContract | null;
}
/**
 * This interface was referenced by `ClusterWireTypesRoot`'s JSON-Schema
 * via the `definition` "WorkerDescriptorWire".
 */
export interface WorkerDescriptorWire {
  artifactProfile: ArtifactResultProfile;
  binding: WorkerProtocolBinding;
  capabilityPolicy: CapabilityPolicy;
  contract: WorkerContract;
  credentialRequirements: CredentialHandle[];
  /**
   * @minItems 1
   */
  graphProfiles: [GraphProfile, ...GraphProfile[]];
  worker: string;
}
