'use strict';

const {
  HOST_SUPERVISOR_RELATIVE_PATH,
  BUN_PACKAGE_NAME,
  BUN_PLATFORM_PACKAGES,
  BUN_RUNTIME_VERSION,
  OMP_NATIVE_PACKAGE_NAME,
  OMP_NATIVE_PLATFORM_PACKAGES,
  OMP_PACKAGE_NAME,
  OMP_SDK_VERSION,
  REQUIRED_OMP_SDK_SOURCES,
  SIDECAR_RELATIVE_PATH,
  assertPackageIdentity,
  resolveOmpSdkRuntime,
} = require('./runtime-identities');
const { validateOmpSdkReleaseAssets } = require('./runtime-release');

module.exports = {
  HOST_SUPERVISOR_RELATIVE_PATH,
  BUN_PACKAGE_NAME,
  BUN_PLATFORM_PACKAGES,
  BUN_RUNTIME_VERSION,
  OMP_NATIVE_PACKAGE_NAME,
  OMP_NATIVE_PLATFORM_PACKAGES,
  OMP_PACKAGE_NAME,
  OMP_SDK_VERSION,
  REQUIRED_OMP_SDK_SOURCES,
  SIDECAR_RELATIVE_PATH,
  assertPackageIdentity,
  resolveOmpSdkRuntime,
  validateOmpSdkReleaseAssets,
};
