//! Client-side NDJSON `agent/attach` subscription coverage: establishment, ordered
//! Working->Output->Settled delivery, cancellation, and unknown/inactive-execution error
//! propagation, driven over the wire against `serve_ndjson`.
//!
//! Generic wire-protocol machinery -- independent request-id sourcing, malformed/unexpected
//! notification handling, and unread-subscription overflow not blocking unary responses -- has no
//! counterpart here: `NdjsonAgentAttachClient`/`NdjsonAgentAttachEventStream` are generated by the
//! exact same [`openengine_cluster_client::ndjson_subscription::impl_ndjson_event_subscription`]
//! macro invocation as `NdjsonLogsClient`/`NdjsonLogsEventStream`, so that machinery is already
//! exhaustively covered once, generically, by `tests/logs.rs`; re-testing it per capability would
//! exercise the exact same generated code a second time.

use std::sync::Arc;

use openengine_cluster_client::{
    AgentAttachEventOrClosed, NdjsonAgentAttachClient, NdjsonAgentAttachEventStream,
    NdjsonTransport,
};
use openengine_cluster_protocol::{
    AgentAttachEvent, AgentAttachParams, BoundedAssistantOutput, ExecutionRef, GONE, NOT_FOUND,
};
use openengine_cluster_server::agent_attach::fixtures::{
    AgentAttachFixtureBackend, AgentAttachFixtureStore,
};
use openengine_cluster_server::watch::fixtures::{await_ndjson_shutdown, spawn_ndjson};
use tokio::io::DuplexStream;

#[path = "cancel_leak_support/mod.rs"]
mod cancel_leak_support;
use cancel_leak_support::assert_cancel_stops_further_delivery;

fn sample_execution_ref() -> ExecutionRef {
    ExecutionRef::new("execution-1").unwrap()
}

fn agent_attach_params() -> AgentAttachParams {
    AgentAttachParams {
        execution: sample_execution_ref(),
    }
}

fn sample_output_event(text: &str) -> AgentAttachEvent {
    AgentAttachEvent::Output {
        text: BoundedAssistantOutput::new(text).unwrap(),
    }
}

/// Awaits the stream's next item and asserts it is the given event, exactly.
async fn expect_next_event(
    stream: &mut NdjsonAgentAttachEventStream<'_, DuplexStream, DuplexStream>,
    expected: &AgentAttachEvent,
) {
    match stream.next().await.unwrap().unwrap() {
        AgentAttachEventOrClosed::Event(event) => assert_eq!(&event, expected),
        other => panic!("expected an event matching {expected:?}, got {other:?}"),
    }
}

#[tokio::test]
async fn establish_stream_working_output_settled_then_cancel_stops_delivery() {
    let store = Arc::new(AgentAttachFixtureStore::new());
    let execution = sample_execution_ref();
    store.register_active(execution.clone()).await;
    let (client_write, client_read, server) =
        spawn_ndjson(AgentAttachFixtureBackend::new(Arc::clone(&store)));

    let transport = NdjsonTransport::new(client_read, client_write);
    let agent_attach_client = NdjsonAgentAttachClient::new(&transport);
    let (_result, mut stream) = agent_attach_client
        .agent_attach(agent_attach_params())
        .await
        .unwrap();

    for event in [
        AgentAttachEvent::Working {},
        sample_output_event("hello"),
        AgentAttachEvent::Settled {},
    ] {
        store.publish(&execution, event.clone()).await;
        expect_next_event(&mut stream, &event).await;
    }

    assert_cancel_stops_further_delivery(
        &mut stream,
        &transport,
        |text| store.publish(&execution, sample_output_event(text)),
        |item| match item {
            AgentAttachEventOrClosed::Event(AgentAttachEvent::Output { text }) => {
                Some(text.as_str().to_owned())
            }
            _ => None,
        },
    )
    .await;

    drop(stream);
    drop(transport);
    await_ndjson_shutdown(server).await;
}

#[tokio::test]
async fn unknown_execution_ref_error_propagates_to_the_client() {
    let store = Arc::new(AgentAttachFixtureStore::new());
    let (client_write, client_read, server) =
        spawn_ndjson(AgentAttachFixtureBackend::new(Arc::clone(&store)));

    let transport = NdjsonTransport::new(client_read, client_write);
    let agent_attach_client = NdjsonAgentAttachClient::new(&transport);
    let Err(error) = agent_attach_client
        .agent_attach(agent_attach_params())
        .await
    else {
        panic!("expected an unknown execution ref to be rejected");
    };
    let openengine_cluster_client::ClientError::Rpc(rpc_error) = error else {
        panic!("expected an RPC error, got {error}");
    };
    assert_eq!(
        rpc_error.data.as_ref().map(|data| data.code.as_str()),
        Some(NOT_FOUND)
    );

    drop(transport);
    await_ndjson_shutdown(server).await;
}

#[tokio::test]
async fn inactive_execution_ref_error_propagates_to_the_client() {
    let store = Arc::new(AgentAttachFixtureStore::new());
    let execution = sample_execution_ref();
    store.register_active(execution.clone()).await;
    store.mark_inactive(&execution).await;
    let (client_write, client_read, server) =
        spawn_ndjson(AgentAttachFixtureBackend::new(Arc::clone(&store)));

    let transport = NdjsonTransport::new(client_read, client_write);
    let agent_attach_client = NdjsonAgentAttachClient::new(&transport);
    let Err(error) = agent_attach_client
        .agent_attach(agent_attach_params())
        .await
    else {
        panic!("expected an inactive execution ref to be rejected");
    };
    let openengine_cluster_client::ClientError::Rpc(rpc_error) = error else {
        panic!("expected an RPC error, got {error}");
    };
    assert_eq!(
        rpc_error.data.as_ref().map(|data| data.code.as_str()),
        Some(GONE)
    );

    drop(transport);
    await_ndjson_shutdown(server).await;
}
